-- MySQL Script generated by MySQL Workbench
-- Wed Dec 10 17:20:44 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `PrincipioAtivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PrincipioAtivo` (
  `idPrincipioAtivo` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idPrincipioAtivo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PrincipioAtivoNome`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PrincipioAtivoNome` (
  `PrincipioAtivo_idPrincipioAtivo` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  INDEX `fk_PrincipioAtivoNome_PrincipioAtivo_idx` (`PrincipioAtivo_idPrincipioAtivo` ASC) VISIBLE,
  PRIMARY KEY (`PrincipioAtivo_idPrincipioAtivo`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE,
  CONSTRAINT `fk_PrincipioAtivoNome_PrincipioAtivo`
    FOREIGN KEY (`PrincipioAtivo_idPrincipioAtivo`)
    REFERENCES `PrincipioAtivo` (`idPrincipioAtivo`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Medicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Medicamento` (
  `idMedicamento` INT NOT NULL AUTO_INCREMENT,
  `nome_comercial` VARCHAR(255) NOT NULL,
  `fabricante` VARCHAR(200) NOT NULL,
  `tipo_medicamento` VARCHAR(100) NOT NULL,
  `controlado` TINYINT NOT NULL,
  PRIMARY KEY (`idMedicamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Embalagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Embalagem` (
  `idEmbalagem` INT NOT NULL AUTO_INCREMENT,
  `Embalar_idMedicamento` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `cod_barras` CHAR(13) NULL,
  PRIMARY KEY (`idEmbalagem`),
  INDEX `fk_Embalagem_Medicamento1_idx` (`Embalar_idMedicamento` ASC) VISIBLE,
  CONSTRAINT `fk_Embalagem_Medicamento1`
    FOREIGN KEY (`Embalar_idMedicamento`)
    REFERENCES `Medicamento` (`idMedicamento`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lote` (
  `idLote` INT NOT NULL AUTO_INCREMENT,
  `Originar_idEmbalagem` INT NOT NULL,
  `codigo` VARCHAR(100) NOT NULL,
  `data_fabricacao` DATE NOT NULL,
  `data_validade` DATE NOT NULL,
  PRIMARY KEY (`idLote`),
  INDEX `fk_Lote_Embalagem1_idx` (`Originar_idEmbalagem` ASC) VISIBLE,
  CONSTRAINT `fk_Lote_Embalagem1`
    FOREIGN KEY (`Originar_idEmbalagem`)
    REFERENCES `Embalagem` (`idEmbalagem`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UnidadeSaude`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UnidadeSaude` (
  `idUnidadeSaude` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idUnidadeSaude`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Farmacia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Farmacia` (
  `idFarmacia` INT NOT NULL AUTO_INCREMENT,
  `Ter_idUnidadeSaude` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `local` VARCHAR(100) NULL,
  PRIMARY KEY (`idFarmacia`),
  INDEX `fk_Farmacia_UnidadeSaude1_idx` (`Ter_idUnidadeSaude` ASC) VISIBLE,
  CONSTRAINT `fk_Farmacia_UnidadeSaude1`
    FOREIGN KEY (`Ter_idUnidadeSaude`)
    REFERENCES `UnidadeSaude` (`idUnidadeSaude`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CaixaMedicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CaixaMedicamento` (
  `idCaixaMedicamento` INT NOT NULL AUTO_INCREMENT,
  `Pertencer_idLote` INT NOT NULL,
  `data_validade_revalidada` DATE NULL,
  `situacao` VARCHAR(20) NOT NULL,
  `Armazenar_idFarmacia` INT NOT NULL,
  PRIMARY KEY (`idCaixaMedicamento`),
  INDEX `fk_CaixaMedicamento_Lote1_idx` (`Pertencer_idLote` ASC) VISIBLE,
  INDEX `fk_CaixaMedicamento_Farmacia1_idx` (`Armazenar_idFarmacia` ASC) VISIBLE,
  CONSTRAINT `fk_CaixaMedicamento_Lote1`
    FOREIGN KEY (`Pertencer_idLote`)
    REFERENCES `Lote` (`idLote`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CaixaMedicamento_Farmacia1`
    FOREIGN KEY (`Armazenar_idFarmacia`)
    REFERENCES `Farmacia` (`idFarmacia`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ComposicaoMedicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ComposicaoMedicamento` (
  `Medicamento_idMedicamento` INT NOT NULL,
  `PrincipioAtivo_idPrincipioAtivo` INT NOT NULL,
  `dosagem_unidade` VARCHAR(30) NOT NULL,
  `dosagem_quantidade` INT NOT NULL,
  PRIMARY KEY (`Medicamento_idMedicamento`, `PrincipioAtivo_idPrincipioAtivo`),
  INDEX `fk_Medicamento_has_PrincipioAtivo_PrincipioAtivo1_idx` (`PrincipioAtivo_idPrincipioAtivo` ASC) VISIBLE,
  INDEX `fk_Medicamento_has_PrincipioAtivo_Medicamento1_idx` (`Medicamento_idMedicamento` ASC) VISIBLE,
  CONSTRAINT `fk_Medicamento_has_PrincipioAtivo_Medicamento1`
    FOREIGN KEY (`Medicamento_idMedicamento`)
    REFERENCES `Medicamento` (`idMedicamento`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medicamento_has_PrincipioAtivo_PrincipioAtivo1`
    FOREIGN KEY (`PrincipioAtivo_idPrincipioAtivo`)
    REFERENCES `PrincipioAtivo` (`idPrincipioAtivo`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Endereco` (
  `cep` CHAR(9) NOT NULL,
  `logradouro` VARCHAR(255) NOT NULL,
  `complemento` VARCHAR(100) NULL,
  `numero` INT NULL,
  `pt_referencia` VARCHAR(100) NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `estado` VARCHAR(100) NOT NULL,
  `UnidadeSaude_idUnidadeSaude` INT NOT NULL,
  INDEX `fk_Endereco_UnidadeSaude1_idx` (`UnidadeSaude_idUnidadeSaude` ASC) VISIBLE,
  PRIMARY KEY (`UnidadeSaude_idUnidadeSaude`),
  CONSTRAINT `fk_Endereco_UnidadeSaude1`
    FOREIGN KEY (`UnidadeSaude_idUnidadeSaude`)
    REFERENCES `UnidadeSaude` (`idUnidadeSaude`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Operador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Operador` (
  `cpf` CHAR(14) NOT NULL,
  `cargo` VARCHAR(100) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VinculoOperadorFarmacia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VinculoOperadorFarmacia` (
  `Operador_cpf` CHAR(14) NOT NULL,
  `Farmacia_idFarmacia` INT NOT NULL,
  `data_inicio` TIMESTAMP NOT NULL,
  `data_fim` TIMESTAMP NOT NULL,
  PRIMARY KEY (`Operador_cpf`, `Farmacia_idFarmacia`),
  INDEX `fk_Operador_has_Farmacia_Farmacia1_idx` (`Farmacia_idFarmacia` ASC) VISIBLE,
  INDEX `fk_Operador_has_Farmacia_Operador1_idx` (`Operador_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_Operador_has_Farmacia_Operador1`
    FOREIGN KEY (`Operador_cpf`)
    REFERENCES `Operador` (`cpf`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Operador_has_Farmacia_Farmacia1`
    FOREIGN KEY (`Farmacia_idFarmacia`)
    REFERENCES `Farmacia` (`idFarmacia`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proposta` (
  `idProposta` INT NOT NULL AUTO_INCREMENT,
  `data_hora` TIMESTAMP NOT NULL,
  `tipo` VARCHAR(15) NOT NULL,
  `quantidade` INT NOT NULL,
  `situacao` VARCHAR(20) NOT NULL,
  `Avaliar_cpf` CHAR(14) NULL,
  `Enviar_cpf` CHAR(14) NULL,
  `Enviar_idFarmacia` INT NOT NULL,
  `Receber_idFarmacia` INT NOT NULL,
  PRIMARY KEY (`idProposta`),
  INDEX `fk_Proposta_Operador1_idx` (`Avaliar_cpf` ASC) VISIBLE,
  INDEX `fk_Proposta_Operador2_idx` (`Enviar_cpf` ASC) VISIBLE,
  INDEX `fk_Proposta_Farmacia1_idx` (`Enviar_idFarmacia` ASC) VISIBLE,
  INDEX `fk_Proposta_Farmacia2_idx` (`Receber_idFarmacia` ASC) VISIBLE,
  CONSTRAINT `fk_Proposta_Operador_Avaliar`
    FOREIGN KEY (`Avaliar_cpf`)
    REFERENCES `Operador` (`cpf`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Proposta_Operador_Enviar`
    FOREIGN KEY (`Enviar_cpf`)
    REFERENCES `Operador` (`cpf`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Proposta_Farmacia_Enviar`
    FOREIGN KEY (`Enviar_idFarmacia`)
    REFERENCES `Farmacia` (`idFarmacia`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Proposta_Farmacia_Receber`
    FOREIGN KEY (`Receber_idFarmacia`)
    REFERENCES `Farmacia` (`idFarmacia`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Movimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Movimento` (
  `idMovimento` INT NOT NULL AUTO_INCREMENT,
  `data_hora` TIMESTAMP NOT NULL,
  `tipo` VARCHAR(30) NOT NULL,
  `Registrar_idCaixaMedicamento` INT NOT NULL,
  `Gerar_idProposta` INT NULL,
  `Autorar_cpf` CHAR(14) NOT NULL,
  `Realizar_idFarmacia` INT NOT NULL,
  PRIMARY KEY (`idMovimento`),
  INDEX `fk_Movimento_CaixaMedicamento1_idx` (`Registrar_idCaixaMedicamento` ASC) VISIBLE,
  INDEX `fk_Movimento_Proposta1_idx` (`Gerar_idProposta` ASC) VISIBLE,
  INDEX `fk_Movimento_Operador1_idx` (`Autorar_cpf` ASC) VISIBLE,
  INDEX `fk_Movimento_Farmacia1_idx` (`Realizar_idFarmacia` ASC) VISIBLE,
  CONSTRAINT `fk_Movimento_CaixaMedicamento1`
    FOREIGN KEY (`Registrar_idCaixaMedicamento`)
    REFERENCES `CaixaMedicamento` (`idCaixaMedicamento`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movimento_Proposta1`
    FOREIGN KEY (`Gerar_idProposta`)
    REFERENCES `Proposta` (`idProposta`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movimento_Operador1`
    FOREIGN KEY (`Autorar_cpf`)
    REFERENCES `Operador` (`cpf`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movimento_Farmacia1`
    FOREIGN KEY (`Realizar_idFarmacia`)
    REFERENCES `Farmacia` (`idFarmacia`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
